# Generated by Django 5.2.13 on 2026-05-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitytimeline_approvalstatuschange_loginattempt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalStatusChange',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
