# Generated by Django 5.2.13 on 2026-05-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_otp_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='attempt_id',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
