# Generated by Django 5.2.13 on 2026-05-08 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fix_attempt_device_id_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('label', models.TextField()),
                ('receiver_name', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'addresses',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='otpsession',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
