# Generated by Django 5.2.13 on 2026-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_use_timestamp_no_tz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('price', models.BigIntegerField(default=0)),
                ('image', models.TextField(blank=True, default='')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('reviews', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True, default='')),
                ('qr_code', models.CharField(blank=True, default='', max_length=50)),
                ('bestseller', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
