# Generated by Django 5.2.13 on 2026-05-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=30, unique=True)),
                ('user_id', models.CharField(max_length=30)),
                ('order_id', models.CharField(blank=True, default='', max_length=30)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='accounts.product', to_field='product_id')),
            ],
            options={
                'db_table': 'reviews',
                'unique_together': {('product', 'user_id', 'order_id')},
            },
        ),
    ]
