# Generated by Django 5.2.13 on 2026-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page_limit',
            field=models.IntegerField(default=3),
        ),
    ]
