# Generated by Django 5.2.13 on 2026-05-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptverification',
            name='pdf_order_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='receiptverification',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
